---
- name: Install software using package managers
  hosts: devserver
  tasks:
    - name: Neovim
      community.general.snap:
        name: nvim
        classic: true
      become: true
    - name: Install Neofetch
      ansible.builtin.apt:
        name: neofetch
        state: present
      become: true
