---
- name: Install software using package managers
  hosts: devserver
  tasks:
    - name: Install bat (batcat)
      ansible.builtin.apt:
        name: bat
        state: present
      become: true
    - name: Install Neofetch
      ansible.builtin.apt:
        name: neofetch
        state: present
      become: true
    - name: Install Neovim
      community.general.snap:
        name: nvim
        classic: true
      become: true
    - name: Install Node.js
      community.general.snap:
        name: node
        classic: true
      become: true
    - name: Install npm
      ansible.builtin.apt:
        name: npm
        state: present
      become: true
    - name: Install ripgrep
      ansible.builtin.apt:
        name: ripgrep
        state: present
      become: true
    - name: Install tmux
      community.general.snap:
        name: tmux
        classic: true
      become: true
    - name: Install pyright globally with npm
      ansible.builtin.npm:
        name: pyright
        global: true
      become: true
